{{- if and (not .Values.database.existingSecret) (not .Values.database.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-app.database.secretName" . }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
