apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notes-app-production

namespace: notes-app-prod

namePrefix: prod-

commonLabels:
  environment: production

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: backend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  - target:
      kind: Deployment
      name: frontend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

  - target:
      kind: HorizontalPodAutoscaler
      name: backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 20

  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "20Gi"
      - op: replace
        path: /spec/storageClassName
        value: "fast-ssd"

images:
  - name: notes-backend
    newTag: v1.0.0
  - name: notes-frontend
    newTag: v1.0.0

patchesStrategicMerge:
  - ingress-tls.yaml 